#!/bin/bash

. "$HOME/.profile"

if [ -f "./mediawikirc" ]
then
        . "./mediawikirc"
fi

if [ -z "$MYSQL_DUMP_FILE" ]
then
	echo "[FATAL] MYSQL_DUMP_FILE not set"
	exit -1
fi
if [ -z "$MYSQL_PASSWORD" ]
then
	echo "[FATAL] MYSQL_PASSWORD not set"
	exit -1
fi

mysqldump --user="$MYSQL_USER" "$MYSQL_DATABASE" --result-file="$MYSQL_DUMP_FILE" --password="$MYSQL_PASSWORD"
