#!/bin/bash

# Script to upgrade MediaWiki core, extensions and skins and install it to intermediate installation directory. Read README.md for details.

. "bash-functions.sh"

upgrade_extensions() {
	log_info "Downloading extensions"
	cd "$EXTENSION_DIRECTORY"
	local IFS=";"
	local EXTENSION_NAME=""
	local EXTENSION_GIT_URL=""
	local EXTENSION_BRANCH=""
	while read EXTENSION_NAME EXTENSION_GIT_URL EXTENSION_BRANCH
	do
		if [ -z "$EXTENSION_NAME" ]
		then
			continue
		fi
		if [ "${EXTENSION_NAME:0:1}" == "#" ]
		then
			continue
		fi
		if [ -z "$EXTENSION_GIT_URL" ]
		then
			EXTENSION_GIT_URL="https://gerrit.wikimedia.org/r/mediawiki/extensions/$EXTENSION_NAME"
		fi
		if [ -z "$EXTENSION_BRANCH" ]
		then
			EXTENSION_BRANCH="$BRANCH"
		fi
		if [ -d "$EXTENSION_DIRECTORY/$EXTENSION_NAME" ]
		then
			cd "$EXTENSION_DIRECTORY/$EXTENSION_NAME"
			log_info "Downloading extension $EXTENSION_NAME"
			git fetch origin "$EXTENSION_BRANCH:$EXTENSION_BRANCH" --depth=1
			handle_error_code "git fetch"
			cd "$EXTENSION_DIRECTORY"
		else
			log_info "Downloading extension $EXTENSION_NAME"
			git clone "$EXTENSION_GIT_URL" --branch "$EXTENSION_BRANCH" --depth=1
			handle_error_code "git clone"
		fi
		if [ -d "$EXTENSION_DIRECTORY/$EXTENSION_NAME" ]
		then
			cd "$EXTENSION_DIRECTORY/$EXTENSION_NAME"
			git checkout "origin/$EXTENSION_BRANCH"
			handle_error_code "git checkout"
			cd "$EXTENSION_DIRECTORY"
		fi
	done < "$EXTENSION_LIST_FILE"
	cd "$CURRENT_DIRECTORY"
}

upgrade_skins() {
	log_info "Downloading skins"

	cd "$SKIN_DIRECTORY"
	local IFS=";"
	local SKIN_NAME=""
	local SKIN_GIT_URL=""
	local SKIN_BRANCH=""
	while read SKIN_NAME SKIN_GIT_URL SKIN_BRANCH
	do
		if [ -z "$SKIN_NAME" ]
		then
			continue
		fi
		if [ "${SKIN_NAME:0:1}" == "#" ]
		then
			continue
		fi
		if [ -z "$SKIN_GIT_URL" ]
		then
			SKIN_GIT_URL="https://gerrit.wikimedia.org/r/mediawiki/skins/$SKIN_NAME"
		fi
		if [ -z "$SKIN_BRANCH" ]
		then
			SKIN_BRANCH="$BRANCH"
		fi
		if [ -d "$SKIN_DIRECTORY/$SKIN_NAME" ]
		then
			cd "$SKIN_DIRECTORY/$SKIN_NAME"
			log_info "Downloading skin $SKIN_NAME"
			git fetch origin "$SKIN_BRANCH:$SKIN_BRANCH" --depth=1
			handle_error_code "git fetch"
			cd "$SKIN_DIRECTORY"
		else
			log_info "Downloading skin $SKIN_NAME"
			git clone "$SKIN_GIT_URL" --branch "$SKIN_BRANCH" --depth=1
			handle_error_code "git clone"
		fi
		if [ -d "$SKIN_DIRECTORY/$SKIN_NAME" ]
		then
			cd "$SKIN_DIRECTORY/$SKIN_NAME"
			git checkout "origin/$SKIN_BRANCH"
			handle_error_code "git checkout"
			cd "$SKIN_DIRECTORY"
		fi
	done < "$SKIN_LIST_FILE"
	cd "$CURRENT_DIRECTORY"
}

copy_extensions() {
	local IFS=";"
	local EXTENSION_NAME=""
	local EXTENSION_GIT_URL=""
	while read EXTENSION_NAME _UNUSED
	do
		if [ -z "$EXTENSION_NAME" ]
		then
			continue
		fi
		if [ "${EXTENSION_NAME:0:1}" == "#" ]
		then
			continue
		fi
		if [ -d "$EXTENSION_DIRECTORY/$EXTENSION_NAME" ]
		then
			log_info "Copying $EXTENSION_NAME"
			cp -r "$EXTENSION_DIRECTORY/$EXTENSION_NAME" "$INTERMEDIATE_MEDIAWIKI_DIRECTORY/extensions"
			cd "$INTERMEDIATE_MEDIAWIKI_DIRECTORY/extensions/$EXTENSION_NAME"
			if [ -f "./composer.json" ]
			then
				"$PHP_EXECUTABLE" "$COMPOSER_EXECUTABLE" update --no-dev
				handle_error_code "composer update"
				"$PHP_EXECUTABLE" "$COMPOSER_EXECUTABLE" install --no-dev
				handle_error_code "composer install"
			fi
			cd "$INTERMEDIATE_MEDIAWIKI_DIRECTORY"
		else
			log_error "$EXTENSION_NAME not found"
		fi
	done < "$EXTENSION_LIST_FILE"
}

copy_skins() {
	local IFS=";"
	local SKIN_NAME=""
	local SKIN_GIT_URL=""
	while read SKIN_NAME _UNUSED
	do
		if [ -z "$SKIN_NAME" ]
		then
			continue
		fi
		if [ "${SKIN_NAME:0:1}" == "#" ]
		then
			continue
		fi
		if [ -d "$SKIN_DIRECTORY/$SKIN_NAME" ]
		then
			log_info "Copying $SKIN_NAME"
			cp -r "$SKIN_DIRECTORY/$SKIN_NAME" "$INTERMEDIATE_MEDIAWIKI_DIRECTORY/skins"
			cd "$INTERMEDIATE_MEDIAWIKI_DIRECTORY/skins/$SKIN_NAME"
			if [ -f "./composer.json" ]
			then
				"$PHP_EXECUTABLE" "$COMPOSER_EXECUTABLE" update --no-dev
				handle_error_code "composer update"
				"$PHP_EXECUTABLE" "$COMPOSER_EXECUTABLE" install --no-dev
				handle_error_code "composer install"
			fi
			cd "$INTERMEDIATE_MEDIAWIKI_DIRECTORY"
		else
			log_error "$SKIN_NAME not found"
		fi
	done < "$SKIN_LIST_FILE"
}

# Settings

CURRENT_DIRECTORY="$(pwd)"

if [ -f "./mediawikirc" ]
then
	. "./mediawikirc"
fi

if [ -z "$COMPOSER_EXECUTABLE" ]
then
	COMPOSER_EXECUTABLE="/usr/local/bin/composer"
fi

if [ -z "$PHP_EXECUTABLE" ]
then
	PHP_EXECUTABLE="php"
fi

if [ -z "$PRESERVED_DIRECTORIES" ]
then
	PRESERVED_DIRECTORIES=("maintenance_custom")
else
	IFS=' ' read -r -a PRESERVED_DIRECTORIES_ARRAY <<< "$PRESERVED_DIRECTORIES"
fi

if [ -z "$PRESERVED_FILES" ]
then
	PRESERVED_FILES_ARRAY=("LocalSettings.php" "do_maintenance")
else
	IFS=' ' read -r -a PRESERVED_FILES_ARRAY <<< "$PRESERVED_FILES"
fi

CORE_DIRECTORY="$CURRENT_DIRECTORY/core"
CORE_MEDIAWIKI_DIRECTORY="$CORE_DIRECTORY/core"
EXTENSION_DIRECTORY="$CURRENT_DIRECTORY/extensions"
SKIN_DIRECTORY="$CURRENT_DIRECTORY/skins"
INTERMEDIATE_DIRECTORY="$CURRENT_DIRECTORY/installation-files"
INTERMEDIATE_MEDIAWIKI_DIRECTORY="$INTERMEDIATE_DIRECTORY/w"
log_info "Intermediate directory (files will be copied here): $INTERMEDIATE_MEDIAWIKI_DIRECTORY"
EXTENSION_LIST_FILE="$CURRENT_DIRECTORY/extension-list.txt"
SKIN_LIST_FILE="$CURRENT_DIRECTORY/skin-list.txt"

TARGET_MEDIAWIKI_DIRECTORY="$MEDIAWIKI_DIR"
log_info "Mediawiki directory: $TARGET_MEDIAWIKI_DIRECTORY"

if [ -z "$BRANCH" ]
then
	log_fatal "BRANCH environment variable not set"
fi

# Updating core

if [ -z "$CORE_ZIP_URL" ]
then
	if [ -d "$CORE_MEDIAWIKI_DIRECTORY" ]
	then
		cd "$CORE_MEDIAWIKI_DIRECTORY"
		log_info "Downloading core"
		git fetch origin "$BRANCH:$BRANCH" --depth=1
		handle_error_code "git fetch"
		git checkout "origin/$BRANCH"
		handle_error_code "git checkout"
	else
		cd "$CORE_DIRECTORY"
		log_info "Downloading core"
		git clone "https://gerrit.wikimedia.org/r/mediawiki/core.git" --branch "$BRANCH" --depth=1
		handle_error_code "git clone"
	fi
else
	if [ -z "$CORE_ZIP_DIR" ]
	then
		log_fatal "CORE_ZIP_URL environment variable is set, but CORE_ZIP_DIR is not set"
	fi
	curl "$CORE_ZIP_URL" --no-clobber --output "$CORE_DIRECTORY/core.zip"
	handle_error_code "curl"
	if [ -d "$CORE_MEDIAWIKI_DIRECTORY" ]
	then
		rm -rf "$CORE_MEDIAWIKI_DIRECTORY"
	fi
	rm -rf "$CORE_DIRECTORY/tmp"
	mkdir -p "$CORE_DIRECTORY/tmp"
	cd "$CORE_DIRECTORY/tmp"
	unzip "$CORE_DIRECTORY/core.zip"
	handle_error_code "unzip"
	cd "$CORE_DIRECTORY"
	mv "$CORE_DIRECTORY/tmp/$CORE_ZIP_DIR" "$CORE_MEDIAWIKI_DIRECTORY"
	handle_error_code "mv"
fi
cd "$CURRENT_DIRECTORY"

# Updating extensions

upgrade_extensions

# Updating skins

upgrade_skins

# Copying to intermediate installation directory

log_info "Copying files"

rm -rf "$INTERMEDIATE_MEDIAWIKI_DIRECTORY"
mkdir -p "$INTERMEDIATE_DIRECTORY"

cp -r "$CORE_MEDIAWIKI_DIRECTORY" "$INTERMEDIATE_MEDIAWIKI_DIRECTORY"
if [ -z "$DONT_PRESERVE_DIRECTORIES" ]
then
	for PRESERVED_DIRECTORY in "${PRESERVED_DIRECTORIES_ARRAY[@]}"
	do
		cp -r "$TARGET_MEDIAWIKI_DIRECTORY/$PRESERVED_DIRECTORY" "$INTERMEDIATE_MEDIAWIKI_DIRECTORY/$PRESERVED_DIRECTORY"
	done
fi
if [ -z "$DONT_PRESERVE_FILES" ]
then
	for PRESERVED_FILE in "${PRESERVED_FILES_ARRAY[@]}"
	do
		cp "$TARGET_MEDIAWIKI_DIRECTORY/$PRESERVED_FILE" "$INTERMEDIATE_MEDIAWIKI_DIRECTORY/$PRESERVED_FILE"
	done
fi

cd "$INTERMEDIATE_MEDIAWIKI_DIRECTORY"
"$PHP_EXECUTABLE" "$COMPOSER_EXECUTABLE" update --no-dev
handle_error_code "composer update"
"$PHP_EXECUTABLE" "$COMPOSER_EXECUTABLE" install --no-dev
handle_error_code "composer install"

copy_extensions

copy_skins

cp -r "$TARGET_MEDIAWIKI_DIRECTORY/skins/common" "$INTERMEDIATE_MEDIAWIKI_DIRECTORY/skins"

find . -name .git -type d -exec rm -rf "{}" \;

cd "$CURRENT_DIRECTORY"

# Finish

log_info "Finished, copied to $INTERMEDIATE_MEDIAWIKI_DIRECTORY"
